# Generated by Django 4.2.4 on 2023-09-22 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_user_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user',
        ),
    ]
